### ISSUE TITLE
Plotting stresses fails in some cases

### ISSUE THREAD

**Issue by ccaprani** [robbievanleeuwen/concrete-properties#84]
The error is deceptive and just appears as matplotlib errors:

<details>
<summary>Click to expand</summary>

```
<AxesSubplot:title={'center':'Pure Bending'}>Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/backends/_backend_tk.py", line 240, in idle_draw
    self.draw()
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super().draw()
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 406, in draw
    self.figure.draw(self.renderer)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/figure.py", line 2790, in draw
    mimage._draw_list_compositing_images(
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2921, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/collections.py", line 350, in draw
    self.update_scalarmappable()
  File "/home/ccaprani/anaconda3/envs/secprop/lib/python3.9/site-packages/matplotlib/collections.py", line 912, in update_scalarmappable
    if self._A.ndim > 1 and not isinstance(self, QuadMesh):
AttributeError: 'list' object has no attribute 'ndim'
```
</details>

I've tracked it back to this line:

https://github.com/robbievanleeuwen/concrete-properties/blob/bbdd6b1a3c5c5ec20fd9ed89fb113c8cfa4d861a/concreteproperties/results.py#L1352

Presumably there is something wrong in the way that the lumped reo patches are being created for my structure. Unfortunately I can't share the structure I'm working on, but I'm parking this low-effort issue notice here and will update if I find out more.

**Comment by ccaprani** [comment]
Interesting...the examples also fail with this error, so it is not my particular section.

<details>
<summary>Code</summary>

```python

import numpy as np
from rich.pretty import pprint
from concreteproperties.material import Concrete, SteelBar
from concreteproperties.stress_strain_profile import (
    EurocodeNonLinear,
    RectangularStressBlock,
    SteelElasticPlastic,
)
from sectionproperties.pre.library.concrete_sections import concrete_circular_section
from concreteproperties.concrete_section import ConcreteSection

concrete = Concrete(
    name="40 MPa Concrete",
    density=2.4e-6,
    stress_strain_profile=EurocodeNonLinear(
        elastic_modulus=32.8e3,
        ultimate_strain=0.0035,
        compressive_strength=40,
        compressive_strain=0.0023,
        tensile_strength=3.8,
        tension_softening_stiffness=10e3,
    ),
    ultimate_stress_strain_profile=RectangularStressBlock(
        compressive_strength=40,
        alpha=0.79,
        gamma=0.87,
        ultimate_strain=0.003,
    ),
    flexural_tensile_strength=3.8,
    colour="lightgrey",
)

steel = SteelBar(
    name="500 MPa Steel",
    density=7.85e-6,
    stress_strain_profile=SteelElasticPlastic(
        yield_strength=500,
        elastic_modulus=200e3,
        fracture_strain=0.05,
    ),
    colour="grey",
)

geom = concrete_circular_section(
    d=600,
    n=32,
    dia=20,
    n_bar=10,
    n_circle=4,
    area_conc=np.pi * 600 * 600 / 4,
    area_bar=310,
    cover=45,
    conc_mat=concrete,
    steel_mat=steel,
)

conc_sec = ConcreteSection(geom)
conc_sec.plot_section()

ultimate_res_pure = conc_sec.ultimate_bending_capacity()

ultimate_stress_pure = conc_sec.calculate_ultimate_stress(
    ultimate_results=ultimate_res_pure
)

ultimate_stress_pure.plot_stress(title="Pure Bending")
```
</details>

**Comment by ccaprani** [comment]
Updating MPL from v3.4.3 has solved this problem. Unfortunately I cannot track back the MPL fix to this problem. However, I checked both v3.5.0 and v3.7.1 and both don't exhibit the problem.

Suggest that a minimum MPL version is included then in CP. PR to follow.
